# Generated by Django 5.1.4 on 2025-03-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('deadline', models.DateField()),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.FileField(upload_to='transcripts/')),
                ('recommendation_letter', models.FileField(upload_to='recommendation_letters/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scholarship')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'scholarship'), name='unique_student_scholarship')],
            },
        ),
    ]
